build: false

environment:
  matrix:
  # Python 2.7
  - MINICONDA: C:\Miniconda
    PYTHON_VERSION: 2.7
    platform: x64
  - MINICONDA: C:\Miniconda-x64
    platform: x86
  # Python 3.4
  - MINICONDA: C:\Miniconda3
    PYTHON_VERSION: 3.4
    platform: x64
  - MINICONDA: C:\Miniconda3-x64
    platform: x86
  # Python 3.5
  - MINICONDA: C:\Miniconda35
    PYTHON_VERSION: 3.5
    platform: x64
  - MINICONDA: C:\Miniconda35-x64
    platform: x86
  # Python 3.6
  - MINICONDA: C:\Miniconda36
    PYTHON_VERSION: 3.6
    platform: x64
  - MINICONDA: C:\Miniconda36-x64
    platform: x86

      
init:
- "ECHO %PYTHON_VERSION% %MINICONDA%"
- "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -q conda
- "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy
  gdal geos cython pandas pyproj beautifulsoup4 fiona ipykernel shapely -c
   conda-forge"
- activate test-environment
- conda update --all -c conda-forge
- "pip install -q pytest pytest-cov coveralls geopandas"
- "pip install -qr requirements.txt"
- "pip install ."
- "echo done"

test_script:
  - pytest


after_test:
  - python.exe setup.py bdist_wheel
  - rm -rf tests/coverages
  - if not exist dist mkdir dist
  - if exist .coverage (cp .coverage dist\) else (echo no .coverage)
  - if exist coverage.xml (cp coverage.xml dist\) else (echo no coverage.xml)

artifacts:
  - path: dist\*
